### ISSUE TITLE
Some error about running code

### ISSUE THREAD

**Issue by xy1234552** [rainmilk/aaai19hers#2]
When I run test_hers, it shows that 'Model' object has no attribute 'predict_aspect_scores', and I check the code and find that the score_model is defined in scorer.py, which don't include 'predict_aspect_scores'.

**Comment by rainmilk** [comment]
Fixed

**Comment by giovanni-bozzano** [comment]
Could you push the updated code together with the missing 'predict_aspect_scores' function?
